Ch 1093 add task version transformation
openHPI/proformaxml pull request #389
Opened 2024-04-18 18:47 UTC by kkoehn

Add the ability to transform tasks between different proforma versions

2024-05-15 16:18 UTC, Dome-GER requested changes

2024-05-15 16:18 UTC, Dome-GER commented on lib/proformaxml/services/exporter.rb
>      # ms-placeholder only necessary for version 2.0 where model-solutions were mandatory
This comment can be removed as well, I'd say.

2024-05-15 16:18 UTC, Dome-GER commented on lib/proformaxml/services/importer.rb
> +      # if version != latest_version
Huh?

2024-05-21 20:25 UTC, kkoehn commented on lib/proformaxml/services/importer.rb
> +      # if version != latest_version
added the planned functionality

2024-07-04 14:57 UTC, Dome-GER approved these changes
I very much like the refactoring into services. It also seems to be tested extensively, I did not dive into all the nitty-gritty details, since I'm lacking some domain knowledge. The overall design decisions look very good,

2024-07-04 14:57 UTC, Dome-GER commented on lib/proformaxml/services/version_and_namespace_extractor.rb
> +      return nil unless potential_namespaces.length == 1
```suggestion
      return unless potential_namespaces.length == 1
```
🤓

2024-07-22 20:10 UTC, merged